replicaCount: 1

image:
  repository: "cr.yandex/crpmeck79ctbb2r5j4j5/tickets"
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []

nameOverride: "tickets"
fullnameOverride: "tickets"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "tickets"

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8070
  name: http

auth:
  auth0:
    domain: "uncledrema.us.auth0.com"
    audience: "https://rsoi.api.com"
    issuerUri: "https://uncledrema.us.auth0.com/"

env:
  - name: SERVER_PORT
    value: "8070"
  - name: SPRING_APPLICATION_NAME
    value: "tickets"
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:postgresql://postgres:5432/tickets"
  - name: SPRING_DATASOURCE_USERNAME
    value: "program"
  - name: SPRING_DATASOURCE_PASSWORD
    value: "test"
  - name: UPSTREAM_GATEWAY
    value: "http://gateway:8080/api/v1"
  - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
    value: "{{ .Values.auth.auth0.issuerUri }}"
  - name: AUTH_AUTH0_DOMAIN
    value: "{{ .Values.auth.auth0.domain }}"
  - name: AUTH_AUTH0_AUDIENCE
    value: "{{ .Values.auth.auth0.audience }}"

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: tickets.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /manage/health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /manage/health
    port: http
  initialDelaySeconds: 20
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 2

nodeSelector: {}
tolerations: []
affinity: {}
