replicaCount: 1

image:
  repository: "cr.yandex/crpmeck79ctbb2r5j4j5/gateway"
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []

nameOverride: "gateway"
fullnameOverride: "gateway"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "gateway"

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8080
  name: http

auth:
  auth0:
    domain: "uncledrema.us.auth0.com"
    audience: "https://rsoi.api.com"
    issuerUri: "https://uncledrema.us.auth0.com/"
    clientId: ""
    clientSecret: ""

env:
  - name: SERVER_PORT
    value: "8080"
  - name: SPRING_APPLICATION_NAME
    value: "gateway"
  - name: DOWNSTREAM_FLIGHTS
    value: "http://flights:8060"
  - name: DOWNSTREAM_TICKETS
    value: "http://tickets:8070"
  - name: DOWNSTREAM_PRIVILEGES
    value: "http://privileges:8050"
  - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
    value: "{{ .Values.auth.auth0.issuerUri }}"
  - name: AUTH_AUTH0_DOMAIN
    value: "{{ .Values.auth.auth0.domain }}"
  - name: AUTH_AUTH0_AUDIENCE
    value: "{{ .Values.auth.auth0.audience }}"
  - name: AUTH_AUTH0_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: "{{ include \"rsoi.fullname\" . }}-auth"
        key: client-id
  - name: AUTH_AUTH0_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: "{{ include \"rsoi.fullname\" . }}-auth"
        key: client-secret

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: 130.193.57.16.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /manage/health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /manage/health
    port: http
  initialDelaySeconds: 20
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 2

nodeSelector: {}
tolerations: []
affinity: {}
