{{- if .Values.auth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rsoi.fullname" . }}-auth
  labels:
    {{- include "rsoi.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.auth.auth0.clientId }}
  client-id: {{ .Values.auth.auth0.clientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.auth0.clientSecret }}
  client-secret: {{ .Values.auth.auth0.clientSecret | b64enc | quote }}
  {{- end }}
{{- end }}
