{{- if and .Values.auth .Values.auth.auth0.clientId .Values.auth.auth0.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rsoi.fullname" . }}-auth
  labels:
    {{- include "rsoi.labels" . | nindent 4 }}
type: Opaque
data:
  client-id: {{ .Values.auth.auth0.clientId | b64enc | quote }}
  client-secret: {{ .Values.auth.auth0.clientSecret | b64enc | quote }}
{{- end }}
